server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: qq
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix= 1
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

    nacos:
      discovery:
        server-addr: 192.168.245.130:8848
  application:
    name: gateway
#            - Path=/serviceVerificationcode/**
#        - id: api-passenger-verification-code
#          uri: lb://api-passenger
#          predicates:
#            - Path=/passenger/**
